// Batch 8 Template - European Architectural Masterpieces
export const BATCH_8_TEMPLATE = [
  {
    id: "22",
    name: "Sagrada Familia",
    location: "Barcelona",
    country: "Spain",
    continent: "Europe",
    type: "Basilica",
    yearBuilt: 2026, // Still under construction, expected completion
    height: 172,
    latitude: 41.4036,
    longitude: 2.1744,
    description: "Antoni Gaudí's masterpiece basilica with unique organic architecture",
    searchTerms: ["Sagrada Familia Barcelona", "Gaudi basilica", "Barcelona cathedral"],
    keyFeatures: ["Organic stone facades", "Colorful spires", "Intricate sculptural details"],
  },
  {
    id: "23",
    name: "Leaning Tower of Pisa",
    location: "Pisa",
    country: "Italy",
    continent: "Europe",
    type: "Bell Tower",
    yearBuilt: 1372,
    height: 56,
    latitude: 43.723,
    longitude: 10.3966,
    description: "Famous tilted bell tower known for its unintended lean",
    searchTerms: ["Leaning Tower Pisa", "Torre di Pisa", "Pisa bell tower"],
    keyFeatures: ["Distinctive tilt", "White marble construction", "Circular design"],
  },
  {
    id: "24",
    name: "Notre-Dame Cathedral",
    location: "Paris",
    country: "France",
    continent: "Europe",
    type: "Cathedral",
    yearBuilt: 1345,
    height: 69,
    latitude: 48.853,
    longitude: 2.3499,
    description: "Gothic cathedral masterpiece on the Île de la Cité",
    searchTerms: ["Notre Dame Paris", "Notre-Dame Cathedral", "Paris Gothic cathedral"],
    keyFeatures: ["Flying buttresses", "Rose windows", "Gothic spires"],
  },
]
